#!/bin/bash
if [ ! -e antlr-4.9.2-complete.jar ]; then
        curl -O https://www.antlr.org/download/antlr-4.9.2-complete.jar
fi

cp="$(pwd)/antlr-4.9.2-complete.jar"
cp2="$(pwd)/h2.jar"
tests="$(pwd)/tests/"
java -Xmx500M -cp ${cp}:. org.antlr.v4.Tool Cypher.g4 
#java -Xmx500M -cp ${cp}:. org.antlr.v4.gui.TestRig Cypher oC_Cypher 

javac -cp ${cp}:${cp2} *.java
java -cp .:${cp}:${cp2} Main ${tests}