#!/bin/bash

name=Simple
jar=antlr-4.13.0-complete.jar
output=gen

rm -rf ${output}
java -cp ${jar} org.antlr.v4.Tool ${name}.g4 -visitor -o ${output}

cp Main.java ${output}
cp test.mu ${output}

( cd ${output}
  javac -cp ${jar} *.java
  java -cp .:${jar} Main
)
